add route prefix option
robertpallas/hapi-plus-routes pull request #12
Opened 2019-05-09 16:41 UTC by heinosasshallik

2019-05-10 09:03 UTC, robertpallas requested changes
Small ideas.

2019-05-10 09:03 UTC, robertpallas commented on README.md
> +  pathPrefix: '/some-prefix',
Just `prefix` is used in Hapi docs, lets keep it simple.

2019-05-10 09:03 UTC, robertpallas commented on index.js
> +          route.path = options.pathPrefix + route.path;
Isn't there a way that route.path does not start with `/`. Just for security would be good to stitch this path together in smarter way with a function that adds slashes if not there.

2019-05-10 11:13 UTC, heinosasshallik commented
I thought it would also be a good idea to add some validation to the route prefix to avoid confusing bugs in case the developer fails to provide the prefix in the correct format.

2019-05-10 12:17 UTC, robertpallas requested changes
Also add basic tests.

2019-05-10 12:17 UTC, robertpallas commented on index.js
> +          if (route.path.charAt(0) !== '/') {
I like `path.posix.join` from https://stackoverflow.com/questions/16301503/can-i-use-requirepath-join-to-safely-concatenate-urls

2019-05-13 10:56 UTC, robertpallas approved these changes

2019-05-13 10:56 UTC, merged